# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Install MCP CLI and dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.12.0 httpx>=0.28.1 xmltodict>=0.14.2 requests>=2.32.4

# Copy application code
COPY . .

# Expose no port since stdio

# Default command
CMD ["python", "weather_server.py"]
