# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project metadata
COPY pyproject.toml .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Copy the application code
COPY . .

# Default command
CMD ["python", "weather_server.py"]
